Repository all-contributors/cli, pull requests merged in 2019-05, with the labels that each got.

#158 feat(init): creates the contributor file if not found
  src/init/__tests__/add-contributors-list.js
  src/init/file-exist.js
  src/init/index.js
Labels: enhancement, priority: medium, status: waiting for feedback

#165 feat: added a JSON handler/fixer
  .gitignore
  package.json
  src/util/config-file.js
Labels: enhancement, priority: medium, status: accepted

#136 feat: init with all-contributors emoji ✨
  src/init/__tests__/__snapshots__/add-contributors-list.js.snap
  src/init/init-content.js
Labels: enhancement, priority: low, status: accepted
