Repository all-contributors/cli, pull requests merged in 2019-11, with the labels that each got.

#213 feat: add review links
  .all-contributorsrc
  README.md
  src/generate/__tests__/format-contribution-type.js
  src/generate/__tests__/format-contributor.js
  src/repo/index.js
  src/util/contribution-types.js
Labels: enhancement, status: review needed

#221 chore(config): bump node
  .circleci/config.yml
Labels: maintenance, priority: medium, status: review needed

#223 feat: add a11y contribution type
  src/util/contribution-types.js
Labels: enhancement, status: in progress

#218 fix: a11y issue by removing unnecessary alternate text (#217)
  src/generate/__tests__/format-contributor.js
  src/generate/format-contributor.js
Labels: enhancement, status: in review
