Repository all-contributors/cli, pull requests merged in 2022-09, with the labels that each got.

#298 chore(deps): bump dependencies and devDeps
  package.json
Labels: status: review needed, maintenance, priority: low, pinned

#139 fix: set default value as `7` for `contributorsPerLine`
  src/generate/index.js
Labels: pinned

#301 feat: adapt to rst
  src/generate/index.js
Labels: enhancement, priority: high, pinned

#163 feat: add footer with link to usage
  .all-contributorsrc
  README.md
  assets/logo-small.svg
  src/generate/__tests__/__snapshots__/index.js.snap
  src/generate/__tests__/index.js
  src/generate/index.js
  src/init/prompt.js
Labels: enhancement, status: in progress, pinned
